apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: apigateway
  name: apigateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
      io.kompose.service: apigateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        app: apigateway
        io.kompose.network/library-default: "true"
        io.kompose.service: apigateway
    spec:
      containers:
        - env:
            - name: CONTAINER_ENV
              value: k8s
          image: kimara19/chassis-apigateway:latest
          name: apigateway
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
            - containerPort: 443
              hostPort: 44340
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
