apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: bookservice
  name: bookservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bookservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/library-default: "true"
        io.kompose.service: bookservice
    spec:
      initContainers:
        - name: wait-for-bookdb
          image: busybox
          command: ['sh', '-c', 'until nc -zv bookdb 1434; do echo waiting for db pod...; sleep 2; done;']
      containers:
        - env:
            - name: DB_HOST
              value: bookdb,1434
            - name: DB_NAME
              value: LibraryBookDB
            - name: DB_SA_PASSWORD
              value: ChassisLibrary123!
          image: kimara19/chassis-bookservice:latest
          name: bookservice
          ports:
            - containerPort: 80
              hostPort: 8082
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
