apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: emailmessageservice
  name: emailmessageservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailmessageservice
      io.kompose.service: emailmessageservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        app: emailmessageservice
        io.kompose.network/library-default: "true"
        io.kompose.service: emailmessageservice
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -zv rabbitmq 5672; do echo waiting for RabbitMQ pod...; sleep 2; done;']
      containers:
        - env:
            - name: RABBITMQSETTINGS__EXCHANGENAME
              value: MailExchange
            - name: RABBITMQSETTINGS__EXCHHANGETYPE
              value: direct
            - name: RABBITMQSETTINGS__QUEUENAME
              value: mail_queue
            - name: RABBITMQSETTINGS__ROUTEKEY
              value: mail_route
            - name: RABBIT_MQ_PASSWORD
              value: guest
            - name: RABBIT_MQ_SERVER
              value: rabbitmq
            - name: RABBIT_MQ_USERNAME
              value: guest
          image: kimara19/chassis-emailmessageservice:latest
          name: emailmessageservice
          ports:
            - containerPort: 80
              hostPort: 8084
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
