apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: reviewservice
  name: reviewservice
  namespace: default
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 80
  selector:
    app: reviewservice
    version: v1
    io.kompose.service: reviewservice
status:
  loadBalancer: {}
