apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: reviewservice
  name: reviewservice-v2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviewservice
      version: v2
      io.kompose.service: reviewservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        app: reviewservice
        version: v2
        io.kompose.network/library-default: "true"
        io.kompose.service: reviewservice
    spec:
      initContainers:
        - name: wait-for-reviewdb
          image: busybox
          command: ['sh', '-c', 'until nc -zv reviewdb 1435; do echo waiting for db pod...; sleep 2; done;']
      containers:
        - env:
            - name: DB_HOST
              value: reviewdb,1435
            - name: DB_NAME
              value: LibraryReviewDB
            - name: DB_SA_PASSWORD
              value: ChassisLibrary123!
            - name: RABBITMQSETTINGS__EXCHANGENAME
              value: MailExchange
            - name: RABBITMQSETTINGS__EXCHHANGETYPE
              value: direct
            - name: RABBITMQSETTINGS__QUEUENAME
              value: mail_queue
            - name: RABBITMQSETTINGS__ROUTEKEY
              value: mail_route
            - name: RABBIT_MQ_PASSWORD
              value: guest
            - name: RABBIT_MQ_SERVER
              value: rabbitmq
            - name: RABBIT_MQ_USERNAME
              value: guest
          image: kimara19/chassis-reviewservice:latest
          name: reviewservice
          ports:
            - containerPort: 80
              hostPort: 8086
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
