apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: reviewdb
  name: reviewdb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reviewdb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/library-default: "true"
        io.kompose.service: reviewdb
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: ChassisLibrary123!
          image: mcr.microsoft.com/mssql/server:2022-latest
          name: reviewdb
          ports:
            - containerPort: 1433
              hostPort: 1435
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
