apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviewservice-mirror
spec:
  hosts:
    - review
  http:
  - route:
    - destination:
        host: reviewservice
        port:
          number: 8003
      weight: 100
    mirror:
      host: reviewservice-v2
      port:
        number: 8006
    mirrorPercentage: 
      value: 100